name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build LaTeX image
        run: make image

      - name: Run tests
        run: RUN_DOCKER_SMOKE_TEST=1 make test
